### ISSUE TITLE
Question about new eggNOG output

### ISSUE THREAD

**Issue by dzolier** [AuReMe/emapper2gbk#14]
Hello, I'm trying to use Metage2Metabo with eggNOG output and MAG bins from metaWRAP, but I didn't get a .faa file when running eggNOG. It appears that eggNOG v2 no longer needs to make a .faa file in order to annotate bins.

I'm curious, is there a way I can use those two outputs -- metaWRAP && eggNOG -- without those .faa files? And if not, is there an alternative method of creating a .faa file?

Thank you for your help.

**Comment by ArnaudBelcour** [comment]
Hi @dzolier,

So you give fastas containing the nucleic sequences of the genomes to eggNOG and it gives you the annotation but not the amino-acids sequences associated with them?
It is strange, because with the version that I have tested, I always get amino-acids sequences (output files with name ending with `.emapper.genepred.fasta`). EggNOG did not produced any of these files?
Which versions among the v2 version of eggNOG do you use?

I could check to see if there is a possibility to put the faa file as optional but this will require to make some test with Pathway Tools to ensure that this causes no issue and I do not have a lot of time right now to test this.

Best regards,
Arnaud Belcour.

**Comment by dzolier** [comment]
I must have just gotten a weird run. I tried it again and everything worked like a charm. Thanks!
